/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-04 14:14:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/jee52/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1753879431000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>회원가입</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/css/join.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"../resources/images/logo.png\" alt=\"Logo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <h2>회원가입</h2>\r\n");
      out.write("  <form action=\"/user/join\" method=\"post\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <label for=\"mbti\">당신의 MBTI를 선택하세요:</label>\r\n");
      out.write("    <select name=\"mbtiId\" id=\"mbti\" required>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"city\">시/도 선택:</label>\r\n");
      out.write("    <select id=\"city\" name=\"city\" required>\r\n");
      out.write("      <option value=\"\">-- 시/도 선택 --</option>\r\n");
      out.write("      <option value=\"서울특별시\">서울특별시</option>\r\n");
      out.write("      <option value=\"부산광역시\">부산광역시</option>\r\n");
      out.write("      <option value=\"대구광역시\">대구광역시</option>\r\n");
      out.write("      <option value=\"인천광역시\">인천광역시</option>\r\n");
      out.write("      <option value=\"광주광역시\">광주광역시</option>\r\n");
      out.write("      <option value=\"대전광역시\">대전광역시</option>\r\n");
      out.write("      <option value=\"울산광역시\">울산광역시</option>\r\n");
      out.write("      <option value=\"세종특별자치시\">세종특별자치시</option>\r\n");
      out.write("      <option value=\"경기도\">경기도</option>\r\n");
      out.write("      <option value=\"강원특별자치도\">강원특별자치도</option>\r\n");
      out.write("      <option value=\"충청북도\">충청북도</option>\r\n");
      out.write("      <option value=\"충청남도\">충청남도</option>\r\n");
      out.write("      <option value=\"전라북도\">전라북도</option>\r\n");
      out.write("      <option value=\"전라남도\">전라남도</option>\r\n");
      out.write("      <option value=\"경상북도\">경상북도</option>\r\n");
      out.write("      <option value=\"경상남도\">경상남도</option>\r\n");
      out.write("      <option value=\"제주특별자치도\">제주특별자치도</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"county\">구/군 선택:</label>\r\n");
      out.write("    <select id=\"county\" name=\"county\" required>\r\n");
      out.write("      <option value=\"\">-- 구/군 선택 --</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"submit\" value=\"가입하기\">\r\n");
      out.write("    <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("  const regionData = {\r\n");
      out.write("      \"서울특별시\": [\"강남구\", \"강동구\", \"강북구\", \"강서구\", \"관악구\", \"광진구\", \"구로구\", \"금천구\", \"노원구\", \"도봉구\", \"동대문구\", \"동작구\", \"마포구\", \"서대문구\", \"서초구\", \"성동구\", \"성북구\", \"송파구\", \"양천구\", \"영등포구\", \"용산구\", \"은평구\", \"종로구\", \"중구\", \"중랑구\"],\r\n");
      out.write("      \"부산광역시\": [\"강서구\", \"금정구\", \"남구\", \"동구\", \"동래구\", \"부산진구\", \"북구\", \"사상구\", \"사하구\", \"서구\", \"수영구\", \"연제구\", \"영도구\", \"중구\", \"해운대구\", \"기장군\"],\r\n");
      out.write("      \"대구광역시\": [\"남구\", \"달서구\", \"동구\", \"북구\", \"서구\", \"수성구\", \"중구\", \"달성군\", \"군위군\"],\r\n");
      out.write("      \"인천광역시\": [\"계양구\", \"남동구\", \"동구\", \"미추홀구\", \"부평구\", \"서구\", \"연수구\", \"중구\", \"강화군\", \"옹진군\"],\r\n");
      out.write("      \"광주광역시\": [\"광산구\", \"남구\", \"동구\", \"북구\", \"서구\"],\r\n");
      out.write("      \"대전광역시\": [\"대덕구\", \"동구\", \"서구\", \"유성구\", \"중구\"],\r\n");
      out.write("      \"울산광역시\": [\"남구\", \"동구\", \"북구\", \"중구\", \"울주군\"],\r\n");
      out.write("      \"세종특별자치시\": [\"세종특별자치시\"],\r\n");
      out.write("      \"경기도\": [\"수원시 장안구\", \"수원시 권선구\", \"수원시 팔달구\", \"수원시 영통구\", \"성남시 수정구\", \"성남시 중원구\", \"성남시 분당구\", \"의정부시\", \"안양시 만안구\", \"안양시 동안구\", \"부천시\", \"광명시\", \"평택시\", \"동두천시\", \"안산시 상록구\", \"안산시 단원구\", \"고양시 덕양구\", \"고양시 일산동구\", \"고양시 일산서구\", \"과천시\", \"구리시\", \"남양주시\", \"오산시\", \"시흥시\", \"군포시\", \"의왕시\", \"하남시\", \"용인시 처인구\", \"용인시 기흥구\", \"용인시 수지구\", \"파주시\", \"이천시\", \"안성시\", \"김포시\", \"화성시\", \"광주시\", \"양주시\", \"포천시\", \"여주시\", \"연천군\", \"가평군\", \"양평군\"],\r\n");
      out.write("      \"강원특별자치도\": [\"춘천시\", \"원주시\", \"강릉시\", \"동해시\", \"태백시\", \"속초시\", \"삼척시\", \"홍천군\", \"횡성군\", \"영월군\", \"평창군\", \"정선군\", \"철원군\", \"화천군\", \"양구군\", \"인제군\", \"고성군\", \"양양군\"],\r\n");
      out.write("      \"충청북도\": [\"청주시 상당구\", \"청주시 서원구\", \"청주시 흥덕구\", \"청주시 청원구\", \"충주시\", \"제천시\", \"보은군\", \"옥천군\", \"영동군\", \"증평군\", \"진천군\", \"괴산군\", \"음성군\", \"단양군\"],\r\n");
      out.write("      \"충청남도\": [\"천안시 동남구\", \"천안시 서북구\", \"공주시\", \"보령시\", \"아산시\", \"서산시\", \"논산시\", \"계룡시\", \"당진시\", \"금산군\", \"부여군\", \"서천군\", \"청양군\", \"홍성군\", \"예산군\", \"태안군\"],\r\n");
      out.write("      \"전라북도\": [\"전주시 완산구\", \"전주시 덕진구\", \"군산시\", \"익산시\", \"정읍시\", \"남원시\", \"김제시\", \"완주군\", \"진안군\", \"무주군\", \"장수군\", \"임실군\", \"순창군\", \"고창군\", \"부안군\"],\r\n");
      out.write("      \"전라남도\": [\"목포시\", \"여수시\", \"순천시\", \"나주시\", \"광양시\", \"담양군\", \"곡성군\", \"구례군\", \"고흥군\", \"보성군\", \"화순군\", \"장흥군\", \"강진군\", \"해남군\", \"영암군\", \"무안군\", \"함평군\", \"영광군\", \"장성군\", \"완도군\", \"진도군\", \"신안군\"],\r\n");
      out.write("      \"경상북도\": [\"포항시 남구\", \"포항시 북구\", \"경주시\", \"김천시\", \"안동시\", \"구미시\", \"영주시\", \"영천시\", \"상주시\", \"문경시\", \"경산시\", \"군위군\", \"의성군\", \"청송군\", \"영양군\", \"영덕군\", \"청도군\", \"고령군\", \"성주군\", \"칠곡군\", \"예천군\", \"봉화군\", \"울진군\", \"울릉군\"],\r\n");
      out.write("      \"경상남도\": [\"창원시 의창구\", \"창원시 성산구\", \"창원시 마산합포구\", \"창원시 마산회원구\", \"창원시 진해구\", \"진주시\", \"통영시\", \"사천시\", \"김해시\", \"밀양시\", \"거제시\", \"양산시\", \"의령군\", \"함안군\", \"창녕군\", \"고성군\", \"남해군\", \"하동군\", \"산청군\", \"함양군\", \"거창군\", \"합천군\"],\r\n");
      out.write("      \"제주특별자치도\": [\"제주시\", \"서귀포시\"]\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("  const citySelect = document.getElementById('city');\r\n");
      out.write("  const countySelect = document.getElementById('county');\r\n");
      out.write("\r\n");
      out.write("  citySelect.addEventListener('change', function () {\r\n");
      out.write("    const selectedCity = this.value;\r\n");
      out.write("    countySelect.innerHTML = '<option value=\"\">-- 구/군 선택 --</option>';\r\n");
      out.write("\r\n");
      out.write("    if (regionData[selectedCity]) {\r\n");
      out.write("      regionData[selectedCity].forEach(function (county) {\r\n");
      out.write("        const option = document.createElement('option');\r\n");
      out.write("        option.value = county;\r\n");
      out.write("        option.textContent = county;\r\n");
      out.write("        countySelect.appendChild(option);\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/user/join.jsp(18,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty OAuthData}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      <input type=\"hidden\" name=\"command\" value=\"OAuthJoin\"/>\r\n");
        out.write("      <input type=\"hidden\" name=\"loginId\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OAuthData.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" />\r\n");
        out.write("      <input type=\"text\" name=\"nickName\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OAuthData.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("      <input type=\"hidden\" name=\"gender\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OAuthData.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" />\r\n");
        out.write("      <input type=\"text\" name=\"birthDate\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OAuthData.birthyear}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('-');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OAuthData.birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" readOnly/>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/user/join.jsp(26,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty OAuthData}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      <input type=\"hidden\" name=\"command\" value=\"join\"/>\r\n");
        out.write("      <input type=\"text\" name=\"loginId\" placeholder=\"아이디 입력\">\r\n");
        out.write("      <input type=\"password\" name=\"password\" placeholder=\"비밀번호 입력\">\r\n");
        out.write("      <label>성별:</label><br>\r\n");
        out.write("      <div class=\"gender-group\">\r\n");
        out.write("        <input type=\"radio\" id=\"male\" name=\"gender\" value=\"M\">\r\n");
        out.write("        <label for=\"male\">남성</label>\r\n");
        out.write("        <input type=\"radio\" id=\"female\" name=\"gender\" value=\"F\">\r\n");
        out.write("        <label for=\"female\">여성</label>\r\n");
        out.write("      </div>\r\n");
        out.write("      <input type=\"text\" name=\"nickName\" placeholder=\"닉네임\">\r\n");
        out.write("      <label for=\"birthDate\">생년월일</label>\r\n");
        out.write("      <input id=\"birthDate\" type=\"date\" name=\"birthDate\">\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/user/join.jsp(45,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("mbti");
    // /WEB-INF/views/user/join.jsp(45,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/join.jsp(45,8) '${mbtiList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${mbtiList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbti.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbti.id == 0 ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(">\r\n");
          out.write("                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbti.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('.');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbti.mbti}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("            </option>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
