/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-02 16:32:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.group;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class create_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>모임 만들기</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>모임 만들기</h2>\r\n");
      out.write("    <form action=\"/group/create\" method=\"post\">\r\n");
      out.write("            <!-- 제목 -->\r\n");
      out.write("            <label for=\"title\">모임 이름</label><br>\r\n");
      out.write("            <input type=\"text\" id=\"title\" name=\"title\" placeholder=\"모임 이름을 입력하세요\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 모임 소개 -->\r\n");
      out.write("            <label for=\"description\">모임 소개</label><br>\r\n");
      out.write("            <textarea id=\"description\" name=\"description\" rows=\"5\" cols=\"40\" placeholder=\"모임을 소개해주세요\" required></textarea><br><br>\r\n");
      out.write("\r\n");
      out.write("           <!-- 시/도 선택 -->\r\n");
      out.write("           <label for=\"city\">시/도 선택:</label><br>\r\n");
      out.write("           <select id=\"city\" name=\"city\" required>\r\n");
      out.write("                   <option value=\"\">-- 시/도 선택 --</option>\r\n");
      out.write("                    <option value=\"서울특별시\">서울특별시</option>\r\n");
      out.write("                    <option value=\"부산광역시\">부산광역시</option>\r\n");
      out.write("                    <option value=\"대구광역시\">대구광역시</option>\r\n");
      out.write("                    <option value=\"인천광역시\">인천광역시</option>\r\n");
      out.write("                    <option value=\"광주광역시\">광주광역시</option>\r\n");
      out.write("                    <option value=\"대전광역시\">대전광역시</option>\r\n");
      out.write("                    <option value=\"울산광역시\">울산광역시</option>\r\n");
      out.write("                    <option value=\"세종특별자치시\">세종특별자치시</option>\r\n");
      out.write("                    <option value=\"경기도\">경기도</option>\r\n");
      out.write("                    <option value=\"강원특별자치도\">강원특별자치도</option>\r\n");
      out.write("                    <option value=\"충청북도\">충청북도</option>\r\n");
      out.write("                    <option value=\"충청남도\">충청남도</option>\r\n");
      out.write("                    <option value=\"전라북도\">전라북도</option>\r\n");
      out.write("                    <option value=\"전라남도\">전라남도</option>\r\n");
      out.write("                    <option value=\"경상북도\">경상북도</option>\r\n");
      out.write("                    <option value=\"경상남도\">경상남도</option>\r\n");
      out.write("                    <option value=\"제주특별자치도\">제주특별자치도</option>\r\n");
      out.write("                  </select><br><br>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 구/군 선택 -->\r\n");
      out.write("                  <label for=\"country\">구/군 선택:</label><br>\r\n");
      out.write("                  <select id=\"country\" name=\"country\" required>\r\n");
      out.write("                    <option value=\"\">-- 구/군 선택 --</option>\r\n");
      out.write("                  </select><br><br>\r\n");
      out.write("\r\n");
      out.write("            <!-- 최대 인원 -->\r\n");
      out.write("            <label for=\"maxUserNum\">최대 인원</label><br>\r\n");
      out.write("            <input type=\"number\" id=\"maxUserNum\" name=\"maxUserNum\" placeholder=\"예: 10\" min=\"1\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            <button type=\"submit\">모임 만들기</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("  const regionData = {\r\n");
      out.write("    '서울특별시': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],\r\n");
      out.write("    '부산광역시': ['강서구', '금정구', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구', '서구', '수영구', '연제구', '영도구', '중구', '해운대구'],\r\n");
      out.write("    '대구광역시': ['남구', '달서구', '달성군', '동구', '북구', '서구', '수성구', '중구'],\r\n");
      out.write("    '인천광역시': ['강화군', '계양구', '남동구', '동구', '미추홀구', '부평구', '서구', '연수구', '옹진군', '중구'],\r\n");
      out.write("    '광주광역시': ['광산구', '남구', '동구', '북구', '서구'],\r\n");
      out.write("    '대전광역시': ['대덕구', '동구', '서구', '유성구', '중구'],\r\n");
      out.write("    '울산광역시': ['남구', '동구', '북구', '중구', '울주군'],\r\n");
      out.write("    '세종특별자치시': ['세종시'],\r\n");
      out.write("    '경기도': ['가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시', '동두천시', '부천시', '성남시', '수원시', '시흥시', '안산시', '안성시', '안양시', '양주시', '양평군', '여주시', '연천군', '오산시', '용인시', '의왕시', '의정부시', '이천시', '파주시', '평택시', '포천시', '하남시', '화성시'],\r\n");
      out.write("    '강원특별자치도': ['강릉시', '고성군', '동해시', '삼척시', '속초시', '양구군', '양양군', '영월군', '원주시', '인제군', '정선군', '철원군', '춘천시', '태백시', '평창군', '홍천군', '화천군', '횡성군'],\r\n");
      out.write("    '충청북도': ['괴산군', '단양군', '보은군', '영동군', '옥천군', '음성군', '제천시', '증평군', '진천군', '청주시', '충주시'],\r\n");
      out.write("    '충청남도': ['계룡시', '공주시', '금산군', '논산시', '당진시', '보령시', '부여군', '서산시', '서천군', '아산시', '예산군', '천안시', '청양군', '태안군', '홍성군'],\r\n");
      out.write("    '전라북도': ['고창군', '군산시', '김제시', '남원시', '무주군', '부안군', '순창군', '완주군', '익산시', '임실군', '장수군', '전주시', '정읍시', '진안군'],\r\n");
      out.write("    '전라남도': ['강진군', '고흥군', '곡성군', '광양시', '구례군', '나주시', '담양군', '목포시', '무안군', '보성군', '순천시', '신안군', '여수시', '영광군', '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군'],\r\n");
      out.write("    '경상북도': ['경산시', '경주시', '고령군', '구미시', '군위군', '김천시', '문경시', '봉화군', '상주시', '성주군', '안동시', '영덕군', '영양군', '영주시', '영천시', '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '칠곡군', '포항시'],\r\n");
      out.write("    '경상남도': ['거제시', '거창군', '고성군', '김해시', '남해군', '밀양시', '사천시', '산청군', '양산시', '의령군', '진주시', '창녕군', '창원시', '통영시', '하동군', '함안군', '함양군', '합천군'],\r\n");
      out.write("    '제주특별자치도': ['서귀포시', '제주시']\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  const citySelect = document.getElementById('city');\r\n");
      out.write("  const countrySelect = document.getElementById('country');\r\n");
      out.write("\r\n");
      out.write("  citySelect.addEventListener('change', function () {\r\n");
      out.write("    const selectedCity = this.value;\r\n");
      out.write("    countrySelect.innerHTML = '<option value=\"\">-- 구/군 선택 --</option>';\r\n");
      out.write("\r\n");
      out.write("    if (regionData[selectedCity]) {\r\n");
      out.write("      regionData[selectedCity].forEach(function (country) {\r\n");
      out.write("        const option = document.createElement('option');\r\n");
      out.write("        option.value = country;\r\n");
      out.write("        option.textContent = country;\r\n");
      out.write("        countrySelect.appendChild(option);\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
